"use client";
import { useCallback, useEffect, useState } from "react";
import { Logo } from "./Logo";
import { teacherRequest, postJson } from "./book-workflow-client";
import { RequestDetails, requestStatus } from "./PrintRequestDetails";
import type { PrintRequest, RequestDocument, ProviderState } from "@/lib/print-requests";
import "./book-workflow.css";
type Dashboard = {
  teachers: { id: string; email: string; name: string; createdAt: string; classroomCount: number; online: number }[];
  classrooms: { id: string; name: string; active: number; teacherName: string; email: string; school: string | null; grade: number | null; classNumber: number | null; rosterCount: number; joinedCount: number; onlineCount: number }[];
  participants: { id: string; nickname: string; seatNumber: number | null; classroomId: string; seenAt: number }[];
  orders: PrintRequest[];
  resources: { scope: string; cores: number; cpuPercent: number | null; usedMemory: number; memoryLimit: number | null; ramPercent: number | null; sampledAt: number };
  capacity: { maximum: number; basis: string; updatedAt: string } | null;
};
const mb = (bytes: number) => `${Math.round(bytes / 1024 / 1024).toLocaleString()} MB`;
export function AdminDashboard({ name }: { name: string }) {
  const [data, setData] = useState<Dashboard | null>(null), [error, setError] = useState(""), [busy, setBusy] = useState("");
  const [tab, setTab] = useState("orders"), [selected, setSelected] = useState(""), [confirmed, setConfirmed] = useState(false), [maximum, setMaximum] = useState(""), [basis, setBasis] = useState("");
  const [detail, setDetail] = useState<PrintRequest | null>(null);
  const load = useCallback(async () => { const value = await teacherRequest<Dashboard>("/api/admin"); setData(value); if (selected) setDetail(await teacherRequest<PrintRequest>(`/api/print-requests/${selected}?kind=detail`)); }, [selected]);
  useEffect(() => { const refresh = () => { if (document.visibilityState === "visible") void load().catch((e) => setError(e.message)); }; refresh(); const timer = setInterval(refresh, 10_000); return () => clearInterval(timer); }, [load]);
  async function action(id: string, fn: () => Promise<void>) { setBusy(id); setError(""); try { await fn(); } catch (e) { setError(e instanceof Error ? e.message : "처리에 실패했어요."); } finally { await load().catch(() => {}); setBusy(""); } }
  const order = detail?.id === selected ? detail : null, provider: ProviderState = order?.provider_json ? JSON.parse(order.provider_json) : {};
  const onlineTeachers = data?.teachers.filter((t) => t.online).length ?? 0, online = (data?.participants.length ?? 0) + onlineTeachers;
  const remaining = data?.capacity ? Math.max(0, data.capacity.maximum - online) : null;
  return <main className="book-desk admin-desk"><header className="book-desk-header"><Logo /><span>운영 관리 · {name}</span><a className="small-button" href="/teacher">교사 화면</a></header><section className="admin-heading"><p className="eyebrow">WIGGLE OPERATIONS</p><h1>교실에서 책이 되기까지</h1><p>가입과 수업 현황, 제작 요청을 한곳에서 확인합니다.</p></section>
    {error && <p className="error-box" role="alert">{error}</p>}
    <div className="admin-metrics"><article><span>가입 교사</span><strong>{data?.teachers.length ?? "—"}</strong></article><article><span>열린 학급</span><strong>{data?.classrooms.filter((c) => c.active).length ?? "—"}</strong></article><article><span>현재 접속 / 운영 최대 인원</span><strong>{online} / {data?.capacity?.maximum ?? "미설정"}</strong><small>학생 {data?.participants.length ?? 0} · 교사 {onlineTeachers}</small></article><article><span>추가 수용 여유</span><strong>{remaining === null ? "산정 전" : `${remaining}명`}</strong><small>{data?.capacity ? "운영 설정 기준 · 입장 제한은 아님" : "부하 테스트 후 최대 인원을 설정하세요"}</small></article></div>
    <nav className="book-toolbar" aria-label="관리 영역">{[["orders", "제작 요청"], ["classes", "교사 · 학급 · 참여자"], ["resources", "서버 · 수용 인원"]].map(([key, label]) => <button key={key} className={`button ${tab === key ? "primary" : "secondary"}`} aria-pressed={tab === key} onClick={() => setTab(key)}>{label}</button>)}</nav>
    {tab === "orders" && <div className="admin-orders"><section className="book-panel"><h2>제작 요청함</h2><p>접수한 파일을 확인하고 견적을 조회한 뒤 발주하세요. 최근 200건을 표시합니다.</p>{data?.orders.map((r) => { const doc: RequestDocument = JSON.parse(r.document_json); return <button className={`admin-request-card ${selected === r.id ? "selected" : ""}`} key={r.id} onClick={() => { setSelected(r.id); setConfirmed(false); }}><b>{doc.classroom.school} {doc.classroom.grade}학년 {doc.classroom.classNumber}반</b><span>{doc.teacher.name} · {doc.items.length}종 / {doc.items.reduce((n, i) => n + i.quantity, 0)}권</span><span>{requestStatus(r.status)}</span><small>{r.created_at} · {r.environment}</small></button>; })}{!data?.orders.length && <p className="book-empty">교사가 제출한 주문 요청서가 여기에 도착합니다.</p>}</section>
      <section className="book-panel"><h2>원고와 주문 요청서</h2>{order ? <><RequestDetails request={order} />{!["submitted", "submitting", "uncertain"].includes(order.status) && <button className="button secondary" disabled={!!busy} onClick={() => void action(order.id, async () => { setConfirmed(false); for (;;) { const r = await teacherRequest<{ done: boolean }>("/api/admin/print-requests", postJson({ id: order.id, action: "prepare" })); await load(); if (r.done) break; } })}>{busy === order.id ? "책별 원고 전송 중…" : "제작사에 원고 준비 · 견적 조회"}</button>}
      {provider.estimate && <div className="book-quote"><h3>제작사 충전금 차감 예정액</h3><strong>{provider.estimate.paidCreditAmount.toLocaleString()}원</strong><p>잔액 {provider.estimate.creditBalance.toLocaleString()}원 · {provider.estimate.creditSufficient ? "발주 가능" : "충전 필요"}</p><p>견적은 10분간 유효합니다. 실제 발주 직전 금액과 잔액을 다시 확인합니다.</p></div>}
      {["quoted", "uncertain", "submitting"].includes(order.status) && <><label className="book-check"><input type="checkbox" checked={confirmed} onChange={(e) => setConfirmed(e.target.checked)} />접수 원고·수량·배송지·충전금 차감 금액을 확인했습니다.</label><button className="button primary" disabled={!!busy || !confirmed || (order.status === "quoted" && !provider.estimate?.creditSufficient)} onClick={() => void action(order.id, async () => { await teacherRequest("/api/admin/print-requests", postJson({ id: order.id, action: "order", confirmed })); setConfirmed(false); })}>{order.status === "quoted" ? order.environment === "live" ? "충전금 결제하고 발주" : "Sandbox 테스트 발주" : "같은 요청으로 발주 결과 확인"}</button></>}
      {order.status === "submitted" && <button className="button secondary" disabled={!!busy} onClick={() => void action(order.id, async () => { await teacherRequest("/api/admin/print-requests", postJson({ id: order.id, action: "refresh" })); })}>제작 · 배송 상태 조회</button>}</> : <p className="book-empty">확인할 제작 요청을 선택하세요.</p>}</section></div>}
    {tab === "classes" && <><section className="book-panel"><h2>가입 교사</h2><div className="admin-table-scroll"><table className="admin-table"><thead><tr><th>교사</th><th>이메일</th><th>가입일</th><th>열린 학급</th><th>접속</th></tr></thead><tbody>{data?.teachers.map((t) => <tr key={t.id}><td>{t.name}</td><td>{t.email}</td><td>{t.createdAt}</td><td>{t.classroomCount}</td><td>{t.online ? "접속 중" : "오프라인"}</td></tr>)}</tbody></table></div></section><section className="book-panel"><h2>학급과 현재 참여자</h2><p>30초마다 접속을 확인하며, 최근 90초 이내 응답한 사람을 표시합니다. 여러 탭은 한 명으로 집계하고, 숨겨진 화면·종료한 화면은 최대 90초 뒤 제외됩니다.</p>{data?.classrooms.map((c) => <article className="book-panel" key={c.id}><h3>{c.school ?? "학교 정보 미등록"} · {c.grade ?? "—"}학년 {c.classNumber ?? "—"}반</h3><p>{c.name} · {c.teacherName} ({c.email}) · {c.active ? "진행 중" : "종료"}</p><p>등록 명단 <b>{c.rosterCount}명</b> / 한 번 이상 입장 <b>{c.joinedCount}명</b> / 현재 접속 <b>{c.onlineCount}명</b></p><div className="admin-participants">{data.participants.filter((p) => p.classroomId === c.id).map((p) => <span key={p.id}>{p.seatNumber ? `${p.seatNumber}번 ` : ""}{p.nickname}</span>)}</div></article>)}</section></>}
    {tab === "resources" && <section className="book-panel"><h2>서버 자원과 수용 인원</h2><p>{data?.resources.scope} · 논리 CPU {data?.resources.cores ?? "—"}개</p><div className="admin-metrics"><article><span>CPU 사용률</span><strong>{data?.resources.cpuPercent == null ? "측정 중" : `${data.resources.cpuPercent.toFixed(1)}%`}</strong><small>대시보드 조회 사이의 사용량</small></article><article><span>RAM 사용률</span><strong>{data?.resources.ramPercent == null ? "할당량 미확인" : `${data.resources.ramPercent.toFixed(1)}%`}</strong><small>{data && mb(data.resources.usedMemory)} / {data?.resources.memoryLimit ? mb(data.resources.memoryLimit) : "할당량 미확인"}</small></article></div><p>Vercel은 요청마다 여러 함수 인스턴스로 확장됩니다. 이 수치는 전체 서비스의 CPU·RAM이나 최대 동시 참여자가 아닙니다. 그림 저장·PDF 생성·AI 요청과 DB·스토리지 한도에 따라 수용 인원이 달라지므로, 현재 사양만으로 남은 인원을 확정할 수 없습니다.</p>
      <h3>검증한 운영 최대 인원 설정</h3>{data?.capacity && <p>현재 {data.capacity.maximum}명 · 근거: {data.capacity.basis}<br />설정 시각 {data.capacity.updatedAt}</p>}<form onSubmit={(e) => { e.preventDefault(); void action("capacity", async () => { await teacherRequest("/api/admin", postJson({ maximum: Number(maximum), basis })); }); }}><label className="book-field">최대 동시 참여자 (학생 + 교사)<input required type="number" min="1" max="100000" value={maximum} onChange={(e) => setMaximum(e.target.value)} /></label><label className="book-field">부하 테스트 조건과 근거<textarea required minLength={3} maxLength={500} value={basis} onChange={(e) => setBasis(e.target.value)} placeholder="예: 배포 사양, 그림 저장 빈도, 동시 접속 테스트 결과" /></label><button className="button primary" disabled={!!busy}>운영 최대 인원 저장</button></form><p className="book-muted">표시는 현재 접속 / 설정한 최대 인원입니다. 추가 수용 여유는 그 차이이며, 자동 입장 차단이나 성능 보증 수치가 아닙니다.</p></section>}
    <p className="book-muted">10초마다 자동 갱신 · {data ? new Date(data.resources.sampledAt).toLocaleTimeString("ko-KR") : "불러오는 중"}</p>
  </main>;
}
